name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Set up NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install frontend dependencies
        working-directory: reposilite-frontend
        run: |
          npm install
      - name: Build frontend
        working-directory: reposilite-frontend
        run: |
          npm run build
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew clean assemble shadowJar
      - name: Retrieve version
        run: |
          echo "::set-output name=VERSION::$(./gradlew properties -q | grep "version: " | awk '{print $2}')"
        id: version
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Reposilite-${{ steps.version.outputs.VERSION }}.jar
          path: reposilite-backend/build/libs/reposilite-${{ steps.version.outputs.VERSION }}.jar
